

CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY,
    GENDER      NVARCHAR2(10),
    CITY        NVARCHAR2(50),
    PIN_CODE    NVARCHAR2(20),
    STATE       NVARCHAR2(50),
    AGE         NUMBER,
    FIRST_NAME  NVARCHAR2(50),
    MIDDLE_NAME NVARCHAR2(50),
    LAST_NAME   NVARCHAR2(50)
);
DESCRIBE USERS;



CREATE TABLE TRAIN (
    TRAIN_NO     INT PRIMARY KEY,
    CAPACITY     INT,
    TRAIN_NAME   NVARCHAR2(50),
    TRAIN_DESC   NVARCHAR2(50),
    DESTINATION  NVARCHAR2(50),
    ARRIVAL_TIME NVARCHAR2(50)
);




CREATE TABLE USER_MOBILE_NO (
    MOBILE_NO   NVARCHAR2(15),
    USER_ID     INT,
    CONSTRAINT fk_mobile_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);


SELECT GLOBAL_NAME FROM GLOBAL_NAME;
GRANT CREATE SESSION
TO RAIL;
 
DESCRIBE TRAIN;

CREATE TABLE STATION (
    STATION_NO   NUMBER PRIMARY KEY,
    ARRIVAL_TIME VARCHAR2(50),
    HAULT        VARCHAR2(50),
    DEPARTURE    VARCHAR2(50),
    NAME         VARCHAR2(50),
    TRAIN_NO     NUMBER,
    CONSTRAINT fk_station_train FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN(TRAIN_NO)
);



CREATE TABLE TICKET (
    TICKET_ID       INT PRIMARY KEY,
    NO_OF_PASSENGER NVARCHAR2(20),
    FIRST_NAME      NVARCHAR2(50),
    TICKET_PRICE    NVARCHAR2(20),          
    PNR_NO          NVARCHAR2(20),
    TRAIN_NO        INT,
    USER_ID          INT,
    STATUS          NVARCHAR2(20)           
        CHECK (STATUS IN ('CONFIRMED', 'RAC', 'WAITING')),
    CONSTRAINT fk_ticket_train FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN(TRAIN_NO),
    CONSTRAINT fk_ticket_user  FOREIGN KEY (USER_ID)  REFERENCES USERS(USER_ID)
);

SELECT TABLE_NAME FROM TABS;


CREATE TABLE PAYMENT (
    PAY_ID    INT PRIMARY KEY,         
    PAY_DATE  NVARCHAR2(50),
    PAY_DESC  NVARCHAR2(50),
    PAID_AMT  NVARCHAR2(50),
    TICKET_ID INT,
    USER_ID       INT,
    CONSTRAINT fk_payment_ticket FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID),
    CONSTRAINT fk_payment_user   FOREIGN KEY (USER_ID)        REFERENCES USERS(USER_ID)
);



CREATE TABLE BOOKS_AND_CANCEL (
    BOOKING_ID   INT PRIMARY KEY,
    USER_ID      INT,
    FIRST_NAME   NVARCHAR2(50),
    BOOKING_DATE NVARCHAR2(50),
    STATUS       NVARCHAR2(20)
        CHECK (STATUS IN ('BOOKED', 'CANCELLED')),
    CONSTRAINT fk_books_user FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);


CREATE TABLE TRAVELS_IN (
    USER_ID    INT,
    TRAIN_NO INT,
    CONSTRAINT fk_travels_user  FOREIGN KEY (USER_ID)       REFERENCES USERS( USER_ID),
    CONSTRAINT fk_travels_train FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN(TRAIN_NO)
);


CREATE TABLE REACHES (
    TRAIN_NO     INT,
    ARRIVAL_TIME NVARCHAR2(50),
    CONSTRAINT fk_reaches_train FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN(TRAIN_NO)
);


CREATE TABLE START_TABLE (
    TRAIN_NO     INT,
    ARRIVAL_TIME VARCHAR2(50),
    CONSTRAINT fk_start_train FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN(TRAIN_NO)
);



CREATE TABLE SHOWS (
    TICKET_ID INT,
    USER_ID     INT,
    CONSTRAINT fk_shows_ticket FOREIGN KEY (TICKET_ID) REFERENCES TICKET(TICKET_ID)
);



SELECT TABLE_NAME FROM TABS;
DESCRIBE START_TABLE;
